# This is the docker compose file to spin up the calibration API 
services: 
    api:
      build: 
        context: .
        dockerfile: Dockerfile
      container_name: cal_api
      ports: 
        - "6969:80"
