[project]
name = "ficus"
version = "0.1.1"
description = "API to handle pulling configuration from SIPE's internal zookeeper server and potentially other config datastores"
readme = "README.md"
requires-python = ">=3.11, <=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "kazoo>=2.10.0",
    "loguru>=0.7.3",
    "pydantic-settings>=2.13.1",
    "types-pyyaml>=6.0.12.20250516",
]

[tool.pytest.ini_options]
pythonpath = ["src", "tests"]

[tool.ruff]
line-length = 100
target-version = "py312"
lint.select = ["E", "F", "C90"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pytest>=8.3.5",
    "ruff>=0.11.5",
    "tox>=4.25.0",
    "tox-uv>=1.25.0",
]

[tool.mypy]
ignore_missing_imports = true
