import re
from pydantic import BaseModel


# class Rig(BaseModel):
#     rig_type: str
#     comp_type: str
#     instance: str


def parse_rigs(rig_input: str):
    if '.' in rig_input and '-' in rig_input: 
        # rigType.instance-compType
        rig_type, rest = rig_input.split('.', 1)
        comp_type, instance = rest.split('-', 1)
    else: 
        # Split by common separators
        parts = re.split(r'[-_ ]', rig_input)
        if len(parts) != 3: 
            raise ValueError(f"Invalid rig format: {rig_input}")
        rig_type, comp_type, instance = parts

    return get_zk_rig_name(f"{rig_type} {comp_type} {instance}")

# This is unsightly but it is what it is
# Ideally we would connect to the database to get this mapping. 
# The deployment infrastructure might change so I am leaving this as the temporary solution.
def get_zk_rig_name(rig: str):
    rigs_list = {
        "aifi-dtn 1 comp": "AIFI-DTN.1-Comp",
        "beh b control": "BEH.B-Control",
        "beh d control": "BEH.D-Control",
        "beh e control": "BEH.E-Control",
        "beh f control": "BEH.F-Control",
        "beh g control": "BEH.G-Control",
        "bergamo 1 acq": "BERGAMO.1-Acq",
        "bfi 10 acq": "BFI.10-Acq",
        "bfi 3 acq": "BFI.3-Acq",
        "bfi 4 acq": "BFI.4-Acq",
        "bfi 5 acq": "BFI.5-Acq",
        "bfi 6 acq": "BFI.6-Acq",
        "bfi 7 acq": "BFI.7-Acq",
        "btvtest 1 acq": "BTVTest.1-Acq",
        "btvtest 1 mon": "BTVTest.1-Mon",
        "btvtest 1 sync": "BTVTest.1-Sync",
        "cam2p 3 acq": "CAM2P.3-Acq",
        "cam2p 3 mon": "CAM2P.3-Mon",
        "cam2p 3 sync": "CAM2P.3-Sync",
        "cam2p 4 acq": "CAM2P.4-Acq",
        "cam2p 4 mon": "CAM2P.4-Mon",
        "cam2p 4 sync": "CAM2P.4-Sync",
        "cam2p 6 acq": "CAM2P.6-Acq",
        "cam2p 6 mon": "CAM2P.6-Mon",
        "cam2p 6 sync": "CAM2P.6-Sync",
        "coldtable 1 acq": "ColdTable.1-Acq",
        "cryostat 11 acq": "Cryostat.11-Acq",
        "cryostat 4 acq": "Cryostat.4-Acq",
        "ds 1 a-acq": "DS.1-A-Acq",
        "ds 1 acq": "DS.1-Acq",
        "ds 1 mon": "DS.1-Mon",
        "ds 1 sync": "DS.1-Sync",
        "dtn 0 comp": "DTN.0-Comp",
        "dtn 1 comp": "DTN.1-Comp",
        "dtn 2 comp": "DTN.2-Comp",
        "englab 2 desktop": "EngLab.2-Desktop",
        "ephys 1 acq": "Ephys.1-Acq",
        "ephys 2 acq": "Ephys.2-Acq",
        "ephys 3 acq": "Ephys.3-Acq",
        "ephys 4 acq": "Ephys.4-Acq",
        "ephys 5 acq": "Ephys.5-Acq",
        "ephys 6 acq": "Ephys.6-Acq",
        "ephys 7 acq": "Ephys.7-Acq",
        "ephys 8 acq": "Ephys.8-Acq",
        "ephys 9 acq": "Ephys.9-Acq",
        "frg 0 a": "FRG.0-A",
        "frg 1 a": "FRG.1-A",
        "frg 1 b": "FRG.1-B",
        "frg 1 c": "FRG.1-C",
        "frg 1 d": "FRG.1-D",
        "frg 10 a": "FRG.10-A",
        "frg 11 a": "FRG.11-A",
        "frg 11 b": "FRG.11-B",
        "frg 12 a": "FRG.12-A",
        "frg 12 b": "FRG.12-B",
        "frg 12 c": "FRG.12-C",
        "frg 12 d": "FRG.12-D",
        "frg 13 a": "FRG.13-A",
        "frg 13 b": "FRG.13-B",
        "frg 13 c": "FRG.13-C",
        "frg 13 d": "FRG.13-D",
        "frg 2 a": "FRG.2-A",
        "frg 2 b": "FRG.2-B",
        "frg 2 c": "FRG.2-C",
        "frg 2 d": "FRG.2-D",
        "frg 3 a": "FRG.3-A",
        "frg 3 b": "FRG.3-B",
        "frg 3 c": "FRG.3-C",
        "frg 3 d": "FRG.3-D",
        "frg 4 a": "FRG.4-A",
        "frg 4 b": "FRG.4-B",
        "frg 4 c": "FRG.4-C",
        "frg 4 d": "FRG.4-D",
        "frg 5 a": "FRG.5-A",
        "frg 5 b": "FRG.5-B",
        "frg 6 a": "FRG.6-A",
        "frg 6 b": "FRG.6-B",
        "frg 6 c": "FRG.6-C",
        "frg 6 d": "FRG.6-D",
        "frg 7 a": "FRG.7-A",
        "frg 7 b": "FRG.7-B",
        "frg 7 c": "FRG.7-C",
        "frg 7 d": "FRG.7-D",
        "frg 8 a": "FRG.8-A",
        "frg 8 b": "FRG.8-B",
        "frg 8 c": "FRG.8-C",
        "frg 8 d": "FRG.8-D",
        "frg 9 a": "FRG.9-A",
        "frg 9 b": "FRG.9-B",
        "frg 9 d": "FRG.9-D",
        "hbtest 1 ctrl": "HBTEST.1-ctrl",
        "hct 1 acq": "HCT.1-Acq",
        "isiv 1 acq": "ISIV.1-Acq",
        "isiv 1 stim": "ISIV.1-Stim",
        "isiv 2 acq": "ISIV.2-Acq",
        "isiv 3 acq": "ISIV.3-Acq",
        "ls 1 storage": "LS.1-Storage",
        "ls 2 storage": "LS.2-Storage",
        "lsis 1 acq": "LSIS.1-Acq",
        "merscope 10 acq": "MERSCOPE.10-Acq",
        "merscope 11 acq": "MERSCOPE.11-Acq",
        "merscope 12 acq": "MERSCOPE.12-Acq",
        "merscope 3 acq": "MERSCOPE.3-Acq",
        "merscope 3 alz": "MERSCOPE.3-Alz",
        "merscope 6 acq": "MERSCOPE.6-Acq",
        "merscope 6 alz": "MERSCOPE.6-Alz",
        "merscope 7 acq": "MERSCOPE.7-Acq",
        "merscope 7 alz": "MERSCOPE.7-Alz",
        "merscope 8 acq": "MERSCOPE.8-Acq",
        "merscope 8 alz": "MERSCOPE.8-Alz",
        "merscope 9 acq": "MERSCOPE.9-Acq",
        "meso 1 acq": "MESO.1-Acq",
        "meso 1 mon": "MESO.1-Mon",
        "meso 1 sync": "MESO.1-Sync",
        "meso 2 acq": "MESO.2-Acq",
        "meso 2 mon": "MESO.2-Mon",
        "meso 2 sync": "MESO.2-Sync",
        "mfs 1 acq": "MFS.1-Acq",
        "mfs 3 acq": "MFS.3-Acq",
        "mfs 4 acq": "MFS.4-Acq",
        "mfs 5 acq": "MFS.5-Acq",
        "mfslap 1 acq": "MFSLap.1-Acq",
        "mp 1 acq": "MP.1-Acq",
        "mp 2 acq": "MP.2-Acq",
        "mp 3 acq": "MP.3-Acq",
        "mp 4 acq": "MP.4-Acq",
        "mp 5 acq": "MP.5-Acq",
        "mpe printer_objet control": "MPE.Printer_objet-Control",
        "mpe teresiad desktop": "MPE.TeresiaD-Desktop",
        "mpe ariellel desktop": "MPE.ariellel-Desktop",
        "mpe behaviormon vm": "MPE.behaviormon-VM",
        "mpe bens desktop": "MPE.bens-Desktop",
        "mpe cliffsl desktop": "MPE.cliffsl-Desktop",
        "mpe cliffsl laptop": "MPE.cliffsl-Laptop",
        "mpe colinf desktop": "MPE.colinf-Desktop",
        "mpe eng logtools-vm": "MPE.eng-logtools-VM",
        "mpe eng shakealert-vm": "MPE.eng-shakealert-VM",
        "mpe eng tools-vm": "MPE.eng-tools-VM",
        "mpe gamma_cal_laptop control": "MPE.gamma_cal_laptop-Control",
        "mpe hestons desktop": "MPE.hestons-Desktop",
        "mpe laser_cutter_trotec control": "MPE.laser_cutter_trotec-Control",
        "mpe martins desktop": "MPE.martins-Desktop",
        "mpe mpe windows-service-vm": "MPE.mpe-windows-service-VM",
        "mpe nathan.mars laptop": "MPE.nathan.mars-Laptop",
        "mpe patrickl desktop": "MPE.patrickl-Desktop",
        "mpe quinn desktop": "MPE.quinn-Desktop",
        "mpe shared_laptop control": "MPE.shared_laptop-Control",
        "mpe tottek desktop": "MPE.tottek-Desktop",
        "nd_ephys 1 beh": "ND_Ephys.1-Beh",
        "nd_ephys 1 ephys": "ND_Ephys.1-Ephys",
        "nd_ephys 2 beh": "ND_Ephys.2-Beh",
        "nd_ephys 2 ephys": "ND_Ephys.2-Ephys",
        "nd_ephys 3 beh": "ND_Ephys.3-Beh",
        "nd_ephys 3 ephys": "ND_Ephys.3-Ephys",
        "nd_ephys 4 beh": "ND_Ephys.4-Beh",
        "nd_ephys 4 ephys": "ND_Ephys.4-Ephys",
        "nd_ephys 5 beh": "ND_Ephys.5-Beh",
        "nd_ephys 5 ephys": "ND_Ephys.5-Ephys",
        "np 0 acq": "NP.0-Acq",
        "np 0 mon": "NP.0-Mon",
        "np 0 sync": "NP.0-Sync",
        "np 1 acq": "NP.1-Acq",
        "np 1 mon": "NP.1-Mon",
        "np 1 sync": "NP.1-Sync",
        "np 2 acq": "NP.2-Acq",
        "np 2 mon": "NP.2-Mon",
        "np 2 sync": "NP.2-Sync",
        "np 3 acq": "NP.3-Acq",
        "np 3 mon": "NP.3-Mon",
        "np 3 sync": "NP.3-Sync",
        "np 4 acq": "NP.4-Acq",
        "np 4 mon": "NP.4-Mon",
        "np 4 sync": "NP.4-Sync",
        "og 1 acq": "OG.1-Acq",
        "og 1 mon": "OG.1-Mon",
        "og 1 sync": "OG.1-Sync",
        "opt 1 acq": "OPT.1-Acq",
        "pds 0 acq": "PDS.0-Acq",
        "pds 1 acq": "PDS.1-Acq",
        "pds 2 acq": "PDS.2-Acq",
        "pds 3 acq": "PDS.3-Acq",
        "pds 4 acq": "PDS.4-Acq",
        "rnascope 1 acq": "RNAScope.1-Acq",
        "rnascope 2 acq": "RNAScope.2-Acq",
        "runner 1 comp": "Runner.1-Comp",
        "runner 2 comp": "Runner.2-Comp",
        "srgry 1 therm": "SRGRY.1-Therm",
        "sandbox 1 comp": "Sandbox.1-Comp",
        "sandbox 1 unit_testing": "Sandbox.1-Unit_testing",
        "temca 1 acq": "TEMCA.1-Acq",
        "temca 2 acq": "TEMCA.2-Acq",
        "temca 3 acq": "TEMCA.3-Acq",
        "temca 4 acq": "TEMCA.4-Acq",
        "temca 5 acq": "TEMCA.5-Acq",
        "temca 6 acq": "TEMCA.6-Acq",
        "vco 1 acq": "VCO.1-Acq",
        "vco 2 acq": "VCO.2-Acq",
        "versa 1 acq": "VERSA.1-Acq",
        "vm_sandbox behaviormon_ansible vm": "VM_Sandbox.behaviormon_ansible-vm",
        "vm_sandbox mfish_lightsheet vm": "VM_Sandbox.mfish_lightsheet-vm",
        "vs200 1 acq": "VS200.1-Acq",
        "washer 1 control": "WASHER.1-Control",
        "wl 1 acq": "WL.1-Acq",
        "wl 2 acq": "WL.2-Acq",
        "wl 3 acq": "WL.3-Acq",
        "wl 4 acq": "WL.4-Acq",
        "wl 5 acq": "WL.5-Acq",
        "wl 6 acq": "WL.6-Acq",
        "wl 7 acq": "WL.7-Acq",
        "wl 8 acq": "WL.8-Acq",
        "zeiss 3 acq": "Zeiss.3-Acq",
        "zeiss 4 acq": "Zeiss.4-Acq",
        "zeiss 5 acq": "Zeiss.5-Acq",
        "platform_9_vm mfish_lightsheet win10": "platform_9_vm.mfish_lightsheet-win10",
        "platform_9_vm win tools-win10": "platform_9_vm.win-tools-win10"
    }

    return rigs_list[rig.lower()]